plugins {
    id 'java'
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.6'
    id 'com.enonic.xp.base'
}

dependencies {
    implementation xplibs.portal
    implementation 'com.enonic.lib:lib-mustache:2.1.1'
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo()
}
